[workspace]
members = [
    "bin",
    "mod_source/foundation", "mod_source/saga_base", "mod_source/slate",
    "proc", "utils",
]
default-members = ["bin"]
resolver = "3"

[workspace.dependencies]
# Stage Dependencies
bevy_ecs = { version = "0.19.0", default-features = false }
wasmtime = "46.0.1"
# wit-bindgen = "0.58.0"

# Bevy:
bevy = "0.18"
# Set max log levels. This helps avoid unwanted low-severity log spam, which can affect performance.
log = { version = "0.4", features = [
    "max_level_debug",
    "release_max_level_warn",
] }
tracing = { version = "0.1", features = [
    "max_level_debug",
    "release_max_level_warn",
] }

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[profile.release]
# Compile the entire crate as one unit.
# Slows compile times, marginal improvements.
codegen-units = 1
# Do a second optimization pass over the entire program, including dependencies.
# Slows compile times, marginal improvements.
lto = "thin"
