[package]
name = "proc"
version = "0.1.0"
edition = "2024"


[lib]
proc-macro = true

[dependencies]
# Required for parsing TokenStreams into structured ASTs
syn = { version = "2.0", features = ["full", "extra-traits", "visit-mut"] }
# Required for turning your AST modifications back into Rust code
quote = "1.0"
proc-macro2 = "1.0.107"
